### ISSUE TITLE
Connection creation timeout on Windows, but not on Linux

### ISSUE THREAD

**Issue by adalinesimonian** [redis-rs/redis-rs#1491]
Possibly related to #1287.

When I create a connection, on Windows, with the below options, I see a very long hang and eventually an `os error 10054`.

<details>
<summary><strong>Cargo.toml</strong></summary>

```toml
[package]
name = "package-name"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
futures = "0.3.31"
redis = { version = "0.28.1", features = ["tokio-comp", "aio", "connection-manager", "tokio-native-tls-comp"] }
tokio = { version = "1.43.0", features = ["fs", "rt-multi-thread", "macros"] }
tokio-macros = "2.5.0"
tokio-native-tls = "0.3.1"
```
</details>

```rs
use anyhow::Context;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let client = redis::Client::open("redis://IP:PORT") // replace with valid URL
        .context("Failed to create Redis client")?;

    let _manager = tokio::time::timeout(
        std::time::Duration::from_secs(10),
        client.get_connection_manager()
    )
        .await
        .context("Timeout connecting to Redis")?
        .context("Failed to connect to Redis")?;

    eprintln!("Connected to Redis.");

    Ok(())
}
```

However, if I compile the same exact code on Fedora in WSL, it works without any issues.

Redis server logs show the following at the debug log level:

```
Accepted CLIENT_IP:PORT
Reading from client: Connection reset by peer
```

If I run the following to test if a TCP connection can at all be established, it works.

```rs
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let addr = "IP:PORT"; // replace with valid addr
    let _stream = tokio::net::TcpStream::connect(addr).await?;
    println!("Connected to {}", addr);
    return Ok(());
}
```

Clients other than redis-rs seem to have no issues connecting to the Redis instance using the same parameters. I am not sure what might be the problem.
