### ISSUE TITLE
get_multiplexed_async_std_connection complains about missing tokio runtime

### ISSUE THREAD

**Issue by UgnilJoZ** [redis-rs/redis-rs#700]
I try to instantiate a multiplexed async connection like the following:
```rs
#[async_std::main]
async fn main() {
    redis::Client::open("redis://127.1/")
        .unwrap()
        .get_multiplexed_async_std_connection()
        .await
        .unwrap();
}
```
In version 0.22, the second unwrap panics with `thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/…/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/net/addr.rs:219:48`:
```toml
[dependencies]
redis = {version = "0.22", features = ["async-std-comp"]}
async-std = { version = "1", features = [ "attributes" ] }
```
The panic vanishes if I change "version" to `0.21`.
