### ISSUE TITLE
Timeout support for async connection?

### ISSUE THREAD

**Issue by TENX-S** [redis-rs/redis-rs#908]
Can we get something like this?
```rust
let conn = client.get_tokio_connection_with_timeout(Duration::from_secs(10)).await?;
```

**Comment by TENX-S** [comment]
I have tried something like this, but it did not work:
```rust
let conn = tokio::time::timeout(Duration::from_secs(10), client.get_tokio_connection()).await??;
```

**Comment by jaymell** [comment]
We should have changes ready to accommodate this in our next release. Stay tuned.

**Comment by nihohit** [comment]
> I tried the code below, it did not work as expected though

What happened, that wasn't expected?

**Comment by TENX-S** [comment]
> > I tried the code below, it did not work as expected though
> 
> What happened, that wasn't expected?

Sorry for not being clear, what I meant was that `tokio::time::timeout` did not cancel `client.get_tokio_connection` after 10 seconds.

**Comment by nihohit** [comment]
@TENX-S that sounds like a bug somewhere. Can you create a reproducing test?

**Comment by TENX-S** [comment]
> @TENX-S that sounds like a bug somewhere. Can you create a reproducing test?

```toml
[dependencies.redis]
version = "0.23"
features = ["tokio-comp", "aio"]

[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread", "time"]
```

```rust
let client = redis::Client::open("redis://127.0.0.1:6379")?;
let conn = tokio::time::timeout(Duration::from_secs(1), client.get_tokio_connection()).await??;
unreachable!()
```
